#!/bin/bash

aliases=("User_Alias USERS=www-user-1, www-user-2, www-user-3"
"Host_Alias HOSTS=www-host-1, www-host-2, www-host-3"
"Cmnd_Alias CMNDS=/usr/sbin/lsof -h, /bin/lslpp, /usr/bin/test, /bin/test, /usr/bin/ls, /bin/ls, /opt/EMLXemlxu/bin/emlxadm, /usr/sbin/fcinfo, /usr/sbin/dmidecode, /usr/sbin/hwinfo, /usr/sbin/ifconfig, /usr/sbin/ndd, /usr/ucb/ps, /usr/sbin/lputil, /usr/sbin/hbacmd, /usr/bin/pfiles, /bin/netstat, /usr/sbin/hwinfo, /usr/sbin/miitool, /sbin/ethtool, /usr/sbin/xe, /usr/sbin/esxcfg-info, /usr/sysv/bin/df, /usr/bin/df, /usr/bin/pargs, /sbin/dladm /usr/sbin/wlmstat")

declare -A aliases1
aliases1[User_Alias]="USERS=www-user-1, www-user-2, www-user-3"
aliases1[Host_Alias]="HOSTS=www-host-1, www-host-2, www-host-3"
aliases1[Cmnd_Alias]="CMNDS=/usr/sbin/lsof -h, /bin/lslpp, /usr/bin/test, /bin/test, /usr/bin/ls, /bin/ls, /opt/EMLXemlxu/bin/emlxadm, /usr/sbin/fcinfo, /usr/sbin/dmidecode, /usr/sbin/hwinfo, /usr/sbin/ifconfig, /usr/sbin/ndd, /usr/ucb/ps, /usr/sbin/lputil, /usr/sbin/hbacmd, /usr/bin/pfiles, /bin/netstat, /usr/sbin/hwinfo, /usr/sbin/miitool, /sbin/ethtool, /usr/sbin/xe, /usr/sbin/esxcfg-info, /usr/sysv/bin/df, /usr/bin/df, /usr/bin/pargs, /sbin/dladm /usr/sbin/wlmstat"

# Parse aliases
#  1 - The haystack
parse_aliases() {
  local haystack="${1}"

  local mode=$(echo "${haystack}"|awk '{print $1}')
  local name=$(echo "${haystack}"|awk 'match($2, /(.*)=/, aliases){print aliases[1]}')
  local objects=$(echo "${haystack}"|tr ' ' '@'|awk 'match($0, /.*=(.*)/, aliases){print aliases[1]}'|tr '@' ' ')

  echo "mode=${mode} name=${name} objects=${objects}"
}

for item in "${aliases[@]}"; do
  echo "Parsing: ${item}..."
  parse_aliases "${item}"
  echo ""
done

for item in "${!aliases1[@]}"; do
  echo "Parsing: ${item} ${aliases1[${item}]}..."
  parse_aliases "${item} ${aliases1[${item}]}"
  echo ""
done

