os:
  - linux
  - osx

before_install:
  - brew update
  - brew outdated bash || brew upgrade bash
  
addons:
  apt:
    packages:
      - sudo
      - bash

language: bash
sudo: required

script:
    - cd test; sudo ./harness