os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -k http://ftp.gnu.org/gnu/bash/bash-4.2.tar.gz | zcat | tar -xf -; cd bash-4.2; ./configure --prefix=/usr/local/bin; sudo make install; sudo bash -c "echo /usr/local/bin/bash >> /private/etc/shells"; cd ~/jas-/sudoadm; fi
  
addons:
  apt:
    packages:
      - sudo
      - bash

language: bash
sudo: required

script:
    - pwd; cd test; sudo ./harness