#!/bin/bash

# First arg should be our sudoadmin tool path
sudoadm=$([ "$1" != "" ] && echo "$1" || echo "../../../sudoadmin")

# First arg should be our configuration file path
config=$([ "$2" != "" ] && echo "$2" || echo "../../assets/config")

# Get our name
prog=$(basename $0)

# Get our current working directory
cwd=$(pwd)

# Retrieve the configuration file so we have some data to work with
if [ ! -f ${config} ]; then
  echo "${prog}: Could not locate configuration data for tests, exiting"
  exit 1
fi

source ${config}

# Check for 'sudoadmin'
if [ ! -f "${sudoadm}" ]; then
  sudoadm=$(find / -type f -name sudoadmin|sort -u|head -1)
fi

# Check for 'sudoers'
if [ ! -f "${file}" ]; then
  file=$(find $(dirname ${config}) -type f -name sudoers|sort -u|head -1)
fi

# Ensure ${cmnd_aliases[@]} is > 0
if [ ${#cmnd_aliases[@]} -gt 0 ]; then

  # Begin iteration of ${cmnd_aliases[@]}
  for data in ${!cmnd_aliases[@]}; do

    # Reset ${items}, ${item} & ${random) to empty
    items=
    item=
    random=

    # Make a temporary copy of ${file}
    name="${tmp_dir}$(basename ${file}).${data}.$RANDOM"
    cp ${file} ${name}

    # Add an alias so we can remove it
    bogus=$(${sudoadm} -Vf ${name} -aC ${data} "${cmnd_aliases[${data}]}")
    if [ $? -ne 0 ]; then
      echo "Failed addition of new '${data}' Cmnd_Alias" && exit 1
    fi

    # Create a needle to search for
    needle="^Cmnd_Alias.*${data}.*"

    # Use ${needle} to create ${haystack} from ${name}
    haystack=$(grep "${needle}" ${name})
    if [ "${haystack}" == "" ]; then
      echo "Failed validation of new '${data}' Cmnd_Alias" && exit 1
    fi

    # Sleep for .1 seconds to accomodate for race conditions
    sleep 1

    # Randomly generate a user to add to the ${data} Cmnd_Alias
    item="/$RANDOM"

    # Now add ${item} the alias ${data}
    bogus=$(${sudoadm} -Vf ${name} -aC ${data} "${item}")
    if [ $? -ne 0 ]; then
      echo "Failed to add '${item}' to '${data}' new Cmnd_Alias" && exit 1
    fi

    # Use ${item} to create ${haystack} from ${name}
    haystack=$(grep "${item}" ${name})
    if [ "${haystack}" == "" ]; then
      echo "Failed validation of '${item}' in '${data}' Cmnd_Alias" && exit 1
    fi

    # Clean up our working file(s)
    rm -f ${name}*
  done
fi

echo "Passed"