#!/bin/bash

# Add & verify User_Alias stanza

# First arg should be our configuration file path
config=$([ "$1" != "" ] && echo "$1" || echo "../../assets/config")

# Get our name
prog=$(basename $0)

# Get our current working directory
cwd=$(pwd)

# Retrieve the configuration file so we have some data to work with
if [ ! -f ${config} ]; then
  echo "${prog}: Could not locate configuration data for tests, exiting"
  exit 1
fi

# Load ${config}
source ${config}

echo "not complete"