#!/bin/bash

# First arg should be our manage-sudoer tool path
sudoadm=$([ "$1" != "" ] && echo "$1" || echo "../../../manage-sudoers")

# First arg should be our configuration file path
config=$([ "$2" != "" ] && echo "$2" || echo "../../assets/config")

# Get our name
prog=$(basename $0)

# Get our current working directory
cwd=$(pwd)

# Retrieve the configuration file so we have some data to work with
if [ ! -f ${config} ]; then
  echo "${prog}: Could not locate configuration data for tests, exiting"
  exit 1
fi

source ${config}

# Check for 'manage-sudoers'
if [ ! -f "${sudoadm}" ]; then
  sudoadm=$(find / -type f -name manage-sudoers|sort -u|head -1)
fi

# Check for 'sudoers'
if [ ! -f "${file}" ]; then
  file=$(find $(dirname ${config}) -type f -name sudoers|sort -u|head -1)
fi

# Ensure ${host_aliases[@]} is > 0
if [ ${#host_aliases[@]} -gt 0 ]; then

  # Begin iteration of ${host_aliases[@]}
  for data in ${!host_aliases[@]}; do

    # Reset ${items}, ${item} & ${random) to empty
    items=
    item=
    random=

    # Make a temporary copy of ${file}
    name="${tmp_dir}$(basename ${file}).${data}.$RANDOM"
    cp ${file} ${name}

    # Add an alias so we can remove it
    bogus=$(${sudoadm} -Vf ${name} -aH ${data} "${host_aliases[${data}]}")
    if [ $? -ne 0 ]; then
      echo "Failed addition of new '${data}' Host_Alias" && exit 1
    fi

    # Create a needle to search for
    needle="^Host_Alias.*${data}.*$(echo "${host_aliases[${data}]}"|sed -e 's|, |.*|g')"

    # Use ${needle} to create ${haystack} from ${name}
    haystack=$(grep "${needle}" ${name})
    if [ "${haystack}" == "" ]; then
      echo "Failed validation of new '${data}' Host_Alias" && exit 1
    fi

    # Sleep for .1 seconds to accomodate for race conditions
    sleep 1

    # Randomly generate a user to add to the ${data} Host_Alias
    item="$(cat /dev/urandom | tr -dc 'a-z0-9' | head -c 8)"

    # Now add ${item} the alias ${data}
    bogus=$(${sudoadm} -Vf ${name} -aH ${data} "${item}")
    if [ $? -ne 0 ]; then
      echo "Failed to add '${item}' to '${data}' new Host_Alias" && exit 1
    fi

    # Use ${item} to create ${haystack} from ${name}
    haystack=$(grep "${item}" ${name})
    if [ "${haystack}" == "" ]; then
      echo "Failed addition of '${item}' in '${data}' Host_Alias" && exit 1
    fi

    # Clean up our working file(s)
    rm -f ${name}*
  done
fi

echo "Passed"