#!/bin/bash

# First arg should be our sudoadm tool path
sudoadm=$([ "$1" != "" ] && echo "$1" || echo "../../../sudoadm")

# First arg should be our configuration file path
config=$([ "$2" != "" ] && echo "$2" || echo "../../assets/config")

# Get our name
prog=$(basename $0)

# Get our current working directory
cwd=$(pwd)

# Retrieve the configuration file so we have some data to work with
if [ ! -f ${config} ]; then
  echo "${prog}: Could not locate configuration data for tests, exiting"
  exit 1
fi

source ${config}

# Check for 'sudoadm'
if [ ! -f "${sudoadm}" ]; then
  sudoadm=$(find / -type f -name sudoadm|sort -u|head -1)
fi

# Check for 'sudoers'
if [ ! -f "${file}" ]; then
  file=$(find $(dirname ${config}) -type f -name sudoers|sort -u|head -1)
fi

# Ensure ${permissions[@]} is > 0
if [ ${#permissions[@]} -gt 0 ]; then

  # Begin iteration of ${permissions[@]}
  for data in ${!permissions[@]}; do

    # Reset ${items}, ${item} & ${random) to empty
    items=
    item=
    random=

    # Make a temporary copy of ${file}
    name="${tmp_dir}$(basename ${file}).${data}.$RANDOM"
    cp ${file} ${name}

    # Add an alias so we can remove it
    bogus=$(${sudoadm} -Vf ${name} -aP ${data} "${permissions[${data}]}")
    if [ $? -ne 0 ]; then
      echo "Failed addition of new '${data}' Permissions"
      echo "${bogus}" && exit 1
    fi

    # Create a needle to search for
    needle="^${data}.*"

    # Use ${needle} to create ${haystack} from ${name}
    haystack=$(grep "${needle}" ${name})
    if [ "${haystack}" == "" ]; then
      echo "Failed validation of new '${data}' Permissions"
      echo "${bogus}" && exit 1
    fi

    # Sleep for .1 seconds to accomodate for race conditions
    sleep 1

    # Randomly generate a user to add to the ${data} Permissions
    item="/$RANDOM"

    # Now add ${item} the alias ${data}
    bogus=$(${sudoadm} -Vf ${name} -aP ${data} "${item}")
    if [ $? -ne 0 ]; then
      echo "Failed to add '${item}' to '${data}' new Permissions"
      echo "${bogus}" && exit 1
    fi

    # Use ${item} to create ${haystack} from ${name}
    haystack=$(grep "${item}" ${name})
    if [ "${haystack}" == "" ]; then
      echo "Failed addition of '${item}' in '${data}' Permissions"
      echo "${bogus}" && exit 1
    fi

    # Clean up our working file(s)
    rm -f ${name}*
  done
fi

echo "Passed"