#!/bin/bash

# First arg should be our sudoadm tool path
sudoadm=$([ "$1" != "" ] && echo "$1" || echo "../../../sudoadm")

# First arg should be our configuration file path
config=$([ "$2" != "" ] && echo "$2" || echo "../../assets/config")

# Get our name
prog=$(basename $0)

# Get our current working directory
cwd=$(pwd)

# Retrieve the configuration file so we have some data to work with
if [ ! -f ${config} ]; then
  echo "${prog}: Could not locate configuration data for tests, exiting"
  exit 1
fi

source ${config}

# Check for 'sudoadm'
if [ ! -f "${sudoadm}" ]; then
  sudoadm=$(find / -type f -name sudoadm|sort -u|head -1)
fi

# Check for 'sudoers'
if [ ! -f "${file}" ]; then
  file=$(find $(dirname ${config}) -type f -name sudoers|sort -u|head -1)
fi

# Ensure ${user_aliases[@]} is > 0
if [ ${#user_aliases[@]} -gt 0 ]; then

  # Begin iteration of ${user_aliases[@]}
  for data in ${!user_aliases[@]}; do

    # Make a temporary copy of ${file}
    name="${tmp_dir}$(basename ${file}).${data}.$RANDOM"
    cp ${file} ${name}

    # Suppress output but handle return code
    bogus=$(${sudoadm} -Vf ${name} -aA ${data} "${user_aliases[${data}]}")
    if [ $? -ne 0 ]; then
      echo "Failed addition of new '${data}' User_Alias"
      echo "${bogus}" && exit 1
    fi

    # Create a needle to search for
    needle="^User_Alias.*${data}.*$(echo "${user_aliases[${data}]}"|sed -e 's|, |.*|g')"

    # Use ${needle} to create ${haystack} from ${name}
    haystack=$(grep "${needle}" ${name})
    if [ "${haystack}" == "" ]; then
      echo "Failed validation of new '${data}' User_Alias"
      echo "${bogus}" && exit 1
    fi

    # Clean up our working file(s)
    rm -f ${name}*
  done
fi

echo "Passed"